name: Lint

on:
  pull_request:
    branches:
      - main
      - feat/skyline

jobs:
  golangci_lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.23.1
          cache: false
      - name: Lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          args: --timeout 10m --verbose