name: Unit Test

on:
  pull_request:
    branches:
      - main
      - feat/skyline

jobs:
  unit_test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v5.0.0
        with:
          go-version: 1.23.1
          cache: false
      - name: Install Cardano tools
        uses: milos-ethernal/cardano-node-action@26dcf8e4b11bef82122de0f64ef7ab3b4fad15a8
        with:
          tag: 8.7.3
      - name: Run Unit Tests
        run: go test -v ./... 